project: 
  type: website
  output-dir: _site
  resources:
    - CNAME
  
website:
  site-url: https://ashleymikali.com
  title: "ash r. ‚ô°"
  favicon: images/bow-favicon.png
  
  sidebar:
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - text: "Home"
        href: index.qmd
      - section: "Projects"
        href: about.qmd
        contents:
          - text: "Spending Habits Analysis"
            href: projects/spending-behavior-model/spending-habits-analysis.qmd
          - text: "Census Data Hackathon"
            href: projects/census-data-hackathon/ar_hackathon.qmd
          - text: "Annals of Eugenics Graphs"
            href: projects/eugenics-journal-graphs/aoe-graphs.qmd
          - text: "Onion Article Classification"
            href: placeholder.qmd
          #- text: "Diabetes Exploration"
            #href: placeholder.qmd
          #- text: "K-Pop Release Radar"
            #href: placeholder.qmd
      - section: "Digital Garden"
        href: garden/garden-home.qmd
        contents:
          - text: "Why R > Python IMO"
            href: garden/crab-cult/crab-cult.qmd
          #- text: "(AI) Hallucination is Humanizing"
          #- text: "In Memoriam: Pre-AI Literacy"
          #- text: "Brain Simulate Machine, or Machine Simulate Brain?"
          #- text: "Humanities == Resistance"
      #- section: "Growth Archive"
        #href: reflections/archive-intro.qmd
        #contents: 
          #- text: "May 2025: Eudaimonia"
            #href: reflections/2025-05/reflection-2025-05.qmd
          
  #page-navigation: true
  back-to-top-navigation: true
  
  page-footer:
    left: "[Ashley Russell ‚ô°](https://github.com/ashleymikali)"
    right: "Made with Quarto & hot cocoa ‚òïÔ∏èüß∏ü§é" 
    
  repo-url: https://github.com/ashleymikali/ashleymikali.github.io
  repo-actions: [source, issue]
      
format:
  html:
    theme:
      - default
    #css: styles.css
      - assets/styles.scss
    grid:
      sidebar-width: 265px
    #toc: true
    #toc-depth: 3